#!/bin/bash

# Install requirements
echo "Install requirements"
wget -O - https://raw.githubusercontent.com/NicolasBoulard/dot-files/master/.bin/additionnal/install-git | bash

echo "Clone dot-files repo"
git clone --bare git@github.com:NicolasBoulard/dot-files.git $HOME/.dot-files

function config {
   git --git-dir=$HOME/.dot-files/ --work-tree=$HOME $@
}
mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no

echo "Install additionnal installation"
bash ~/.bin/additionnal/install-exa

echo "Running update"
sudo apt update
echo "Install system requirements"
cat ~/.bin/additionnal/requirements.system | xargs sudo apt install -y

echo "Install Ansible"
bash ~/.bin/additionnal/install-ansible

echo "Install oh-my-zsh"
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
export CHSH=yes
export KEEP_ZSHRC=yes
export RUNZSH=no
chmod u+x install.sh
./install.sh
rm install.sh

echo "Install p10k theme"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

echo "Install ZSH custom plugins"
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo "Install packer"
bash ~/.bin/additionnal/install-packer

echo "Install terraform"
bash ~/.bin/additionnal/install-terraform

echo "Install kubectl"
apt-get install -y apt-transport-https ca-certificates curl
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install -y kubectl

echo "Install helm"
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
rm -rf get_helm.sh

sudo chsh -s /bin/zsh nicolas
