#!/bin/bash
sudo apt install curl -y
. /etc/os-release
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add 
sudo echo -e "deb https://apt.releases.hashicorp.com ${VERSION_CODENAME} main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt-get update && sudo apt-get install packer -y
