#!/bin/bash
GIT_PACKAGE_URL="https://github.com/git/git/archive/refs/heads/master.zip"
echo "Let's install git because APT has older version 🧐"
sudo apt-get update
sudo apt-get install -y make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip wget

wget -P /tmp -q $GIT_PACKAGE_URL
unzip -o -d /tmp/$(basename "$GIT_PACKAGE_URL")_dir /tmp/$(basename "$GIT_PACKAGE_URL")
cd /tmp/$(basename "$GIT_PACKAGE_URL")_dir/git-master/
sudo make prefix=/usr/local all
sudo make prefix=/usr/local install
echo "Git installed with version $(git --version) ! "

